DoAnCuoiKi/Models/SanPham.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DoAnCuoiKi.Models
{
    public class SanPham
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public double Price { get; set; }
        public string? Description { get; set; }
        public string? ImageUrl { get; set; }
        public string? Categories { get; set; }

        [Required]
        public int TheLoaiId { get; set; }
        [ForeignKey("TheLoaiId")]
        [ValidateNever]
        public TheLoai TheLoai { get; set; }
    }
}

DoAnCuoiKi/Areas/Admin/Controllers/SanPhamController.cs
using DoAnCuoiKi.Data;
using DoAnCuoiKi.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace DoAnCuoiKi.Areas.Admin.Controllers
    {
    [Area("Admin")]
    public class SanPhamController : Controller
    {
        private readonly ApplicationDbContext _db;

        public SanPhamController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<SanPham> sanpham = _db.SanPham.ToList();
            return View(sanpham);
        }

        [HttpGet]

        public IActionResult Upsert(int id)
        {
            SanPham sanpham = new SanPham();
            IEnumerable<SelectListItem> dstheloai = _db.TheLoai.Select(
                item => new SelectListItem
                {
                    Value = item.Id.ToString(),
                    Text = item.Name    
                });
            ViewBag.DSTheLoai = dstheloai;
            
            if(id == 0)
            {
                return View(sanpham);
            }
            
            else
            {
                sanpham = _db.SanPham.Include("TheLoai").FirstOrDefault(sp => sp.Id == id);
                return View(sanpham);

            }
        }

        [HttpPost]
        public IActionResult Upsert(SanPham sanpham)
        {
            if(ModelState.IsValid)
            {
                if(sanpham.Id == 0)
                {
                    _db.SanPham.Add(sanpham);
                }

                else
                {
                    _db.SanPham.Update(sanpham);
                }
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        //Delete   
        [HttpPost]
        public IActionResult Delete(int id)
        {
            var sanpham = _db.SanPham.FirstOrDefault(sp => sp.Id == id);
            if(sanpham == null)
            {
                return NotFound();
            }
            _db.SanPham.Remove(sanpham);
            _db.SaveChanges();  
            return Json(new { success = true});               
        }

    }
}

DoAnCuoiKi/Areas/Admin/Views/SanPham/Index.cshtml
@model IEnumerable<SanPham>

<style>
    table, thead, td
    {
        border:2px solid black;
        text-align: center;
    }

    .Action a{
        text-decoration: none;
        color:black;        
    }
    a:hover{
        color: orange;
    }
    .btn{
        color:white;
    }
</style>

<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Price</th>
                <th>ImageUrl</th>
                <th>TheLoaiId</th>
                <th> Chức năng</th>
            </tr>
        </thead>

        @foreach(var item in @Model)
        {
            <tbody>
                <tr>
                    <td>@item.Name</td>
                    <td>@item.Description</td>
                    <td>@item.Price</td>
                    <td>...</td>
                    <td>@item.TheLoaiId</td>
                    <td witdh="40%">
                        <a asp-action="Upsert" asp-route-id = "@item.Id">Edit</a> |
                        <a class="btn btn-primary" onclick="xoa(@item.Id, $(this))">Delete</a> 
                    </td>
                </tr>
            </tbody>
        }
    </table>
    <a asp-controller="SanPham" asp-action="Upsert" class="btn btn-primary">Thêm mới</a>
</div>

@*AJAX*@
<script>
    function xoa(id, row){                          
        $.ajax ({
        url : `/Admin/SanPham/Delete/${id}`,
        type: "POST",
        })
        .done(function (data){
            row.closest("tr").remove();
        })
    }
</script>

DoAnCuoiKi/Areas/Admin/Views/SanPham/Upsert.cshtml
@model SanPham
@{
    ViewData["Title"] = "UpSert";
}

<div class="container">
    <h3>Thêm mới và Update</h3>
    <form method="post" asp-action="UpSert">

        <div class="form-group">
            <label asp-for="Name">Tên sản phẩm</label>
            <input asp-for="Name" type="text" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        
        <div class="form-group">
            <label asp-for="Description">Mô tả</label>
            <input asp-for="Description" type="text" class="form-control" />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        
        <div class="form-group">
            <label asp-for="Price">Giá</label>
            <input asp-for="Price" type="number" class="form-control" />
            <span asp-validation-for="Price" class="text-danger"></span>
        </div>
        
        <div class="form-group">
            <label asp-for="ImageUrl">Hình ảnh</label>
            <input asp-for="ImageUrl" type="text" class="form-control" />
            <span asp-validation-for="ImageUrl" class="text-danger"></span>
        </div>
        
        <div class="form-group">
            <label asp-for="TheLoaiId">Thể loại</label>
            <select asp-for="TheLoaiId" asp-items="@ViewBag.DsTheLoai" class="form-control">
                <option selected disabled>Chọn thể loại</option>
            </select>
            <span asp-validation-for="TheLoaiId" class="text-danger"></span>
        </div>
        <br><br>
        <button type="submit" class="btn btn-primary">Tạo mới</button>
        <a asp-action="Index" class="btn btn-secondary">Hủy</a>
    </form>
</div>

@section Scripts
{
    <partial name ="_ValidationScriptsPartial"/>
}